default: &default
  asset_host:
    carrierwave: <%= ENV['UPLOADED_ASSET_HOST'] || 'http://localhost:3000' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  asset_host:
    carrierwave: <%= ENV['UPLOADED_ASSET_HOST'] || 'https://example.com/' %>
